db.technologies.insertOne([
    "HTML",
    "CSS",
    "SCSS",
    "SASS",
    "PostCSS",
    "Bootstrap",
    "Tailwind",
    "JavaScript",
    "TypeScript",
    "React",
    "React Native",
    "Ant Design",
    "Material UI",
    "Angular",
    "Vue.js",
    "Node.js",
    "Electron",
    "Express.js",
    "Three.js",
    "Webpack",
    "Babel",
    "MongoDB",
    "MySQL",
    "PostgreSQL", 
    "SQL Server",
    "GraphQL",
    "Java",
    "Python",
    "Django",
    "Flask",
    "Ruby",
    "Ruby on Rails",
    "PHP",
    "Laravel",
    "C#",
    ".NET",
    ".NET Framework",
    ".NET Core",
    "ASP.NET",
    "Xamarin",
    "Swift",
    "Objective-C",
    "Kotlin",
    "Dart",
    "Flutter",
    "Go",
    "Rust",
    "Azure",
    "Azure Web Services",
    "Google Cloud Platform",
    "Firebase",
    "Docker",
    "Docker Compose",
    "Grafana",
    "Kubernetes",
    "Jenkins",
    "Travis CI",
    "Git",
    "GitHub",
    "Bitbucket",
    "GitLab",
    "JIRA",
    "Agile",
    "Scrum",
    "Kanban",
    "DevOps",
    "REST API",
    "UI",
    "Figma",
    "Sketch",
    "UX",
    "VR",
    "AR",
    "ARKit",
    "ARCore",
    "A-Frame",
    "AR.js",
    "Machine Learning",
    "Natural Language Processing",
    "Apache Hadoop",
    "Apache Spark",
    "Apache Cordova",
    "Game development",
    "Unity",
    "Unreal Engine"
])